### PR TITLE
TSV-ify the download images

### LINKED ISSUE #238: Update download images: single_cell_metadata is a tsv, not csv
While working on merged docs, I noticed a _general discrepancy_ between _all_ of our images and the actual downloads themselves.

- All of our download images indicate a metadata file (caps for emphasis) `single_cell_metadata.CSV`, but the actual file itself is a `single_cell_metadata.TSV`. I confirmed this by downloading a sample from the portal.
  - See images here (same situation in the `development` branch) : https://github.com/AlexsLemonade/scpca-docs/tree/main/docs/images 
- The docs themselves state that it is a TSV, as well: https://github.com/AlexsLemonade/scpca-docs/blob/d7c2b4db3c75eb08530518c103fa23afc090ab8c/docs/download_files.md?plain=1#L67 

So, I suppose we need to update all of the images with the correct extension. 
FYI @dvenprasad

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #238 

This PR updates all current download images (not including merged) to reflect that all our metadata files are `.tsv`, not `.csv`. 

There is one additional change here - the spaceranger report along the way got renamed with a `-`; it was `library_spaceranger_summary.html`, now `library_spaceranger-summary.html`. I didn't notice this in #238, but saw it here when I filed the PR. I think it's a good move with other naming changes. The other consequences of this are we have to update the name in `scpca-nf` (quick fix), and we'd also have to update the file names in the Portal (I guess we can manually rename in prod and include in handoff). Or, we can revert the image back to an `_`. 

Since the reports include the cell type reports, we should only release these updated images with the cell type release, not anndata. So, I'll cherry pick into the cell type release PR once this goes into `development`. Also, I would note in that CHANGELOG that the spatial summary report name has been tweaked.

### CODE REVIEW

**Comment by allyhawkins** [comment]
> The other consequences of this are we have to update the name in scpca-nf (quick fix), and we'd also have to update the file names in the Portal (I guess we can manually rename in prod and include in handoff). Or, we can revert the image back to an _.

I'm fine with making this name change, but given that we aren't going to include these docs changes until cell type annotation, anything that's already handed off can stay the way it is. I don't want to manually rename since there's like 100 samples of spatial, but I would be fine with including this in the release of `scpca-nf` with the bug fixes (https://github.com/AlexsLemonade/scpca-nf/issues/669) and re-running that project before we hand off cell typing.

**Comment by sjspielman** [comment]
>  but given that we aren't going to include these docs changes until cell type annotation, anything that's already handed off can stay the way it is. 

Yes, definitely.

> I would be fine with including this in the release of scpca-nf with the bug fixes (https://github.com/AlexsLemonade/scpca-nf/issues/669) and re-running that project before we hand off cell typing.

I'll make an issue in admin that blocks the release.

**Review by allyhawkins — COMMENTED** [review]
Before I approve this: 
- The text in the spatial section should be updated to reflect the new name (https://github.com/AlexsLemonade/scpca-docs/blob/sjspielman/238-tsv-images/docs/download_files.md#spatial-transcriptomics-libraries). 
- We need an issue in `scpca-nf` to update the filename for the spatial summary and have that issue block the release. 
- And then a comment on https://github.com/AlexsLemonade/ScPCA-admin/issues/730 about re-running SCPCP000006 prior to hand-off.

**Comment by sjspielman** [comment]
- [X] The text in the spatial section should be updated to reflect the new name (https://github.com/AlexsLemonade/scpca-docs/blob/sjspielman/238-tsv-images/docs/download_files.md#spatial-transcriptomics-libraries).
  - https://github.com/AlexsLemonade/scpca-docs/pull/257/commits/134cd3c4429cae3b56c4c8b28777b20fceee3f4e
- [ ] We need an issue in `scpca-nf` to update the filename for the spatial summary and have that issue block the release.
  - https://github.com/AlexsLemonade/scpca-nf/issues/678 
- [ ] And then a comment on [Process projects with known references through cell type annotation ScPCA-admin#730](https://github.com/AlexsLemonade/ScPCA-admin/issues/730) about re-running SCPCP000006 prior to hand-off.
  - https://github.com/AlexsLemonade/ScPCA-admin/issues/730#issuecomment-1915142886
- [ ] SJS: Add to cell type docs CHANGELOG 
  - https://github.com/AlexsLemonade/scpca-docs/pull/223/commits/4aaec072cc3b2b99e8af2627046f8089cfbae473

**Comment by sjspielman** [comment]
> but I think that's a question for @dvenprasad.

Stay tuned!

**Comment by sjspielman** [comment]
Ok, it's a no, so I'll revert that commit!

**Pull request merged**
