### PR TITLE
Add build.os argument to config

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
Our builds are broken. I think this is why!

If this works and goes in, we'll need to file PRs to `development` and `documentation-improvements`.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
I told RTD it lives in `docs/` in the RTD interface, but I can undo that.

**Comment by allyhawkins** [comment]
> I told RTD it lives in docs/ in the RTD interface, but I can undo that.

Ah okay, we can keep it in `docs`, we just will need to move it for `development`, which I think is fine.

**Review by allyhawkins — APPROVED** [review]
Going to go ahead and approve 👍

**Comment by jaclyn-taroni** [comment]
> I told RTD it lives in `docs/` in the RTD interface, but I can undo that.

That feature is experimental, so we might as well go with the solution already in `development`. Hold please!

**Comment by jaclyn-taroni** [comment]
@allyhawkins this could use another look now that I've changed strategies!

**Review by allyhawkins — APPROVED** [review]
LGTM

**Pull request merged**
