### PR TITLE
Incorporate corrected download file images

### LINKED ISSUE #226: Corrected download folder images
QC and Cell Type reports in the illustration did not match how they were named in the the downloads. Here are the illustrations with those corrections. 

**SCE Project Download**
sc-project-download-folder

**SCE Sample Download**
sc-sample-download-folder

**AnnData Project Download**
anndata-project-download-folder

**AnnData Sample Download**
anndata-sample-download-folder

**AnnData CITE-seq Sample Download**
anndata-CITE-seq-sample-download-folder

**Multiplexed Download**
multiplexed-download-folder

@allyhawkins Let me know if you need anything else or if I've missed anything.

### PR DESCRIPTION
**Pull request by allyhawkins**
Closes #226 

Here I just replaced the old images with the ones @dvenprasad updated in #226. Once this is merged I'll cherry pick the commit to make sure it's incorporated to the cell type branch.

### CODE REVIEW

**Comment by sjspielman** [comment]
This has `_celltype_report`? I thought we're expecting `_celltype-report`?

**Comment by allyhawkins** [comment]
It would help if I added the correct images from that issue...

**Comment by allyhawkins** [comment]
Should be good to go now @sjspielman

**Review by sjspielman — APPROVED** [review]
🐳

**Pull request merged**
